const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const { pathToFileURL } = require('url');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const out = path.join(__dirname, 'results');
fs.mkdirSync(out, { recursive: true });
const url = pathToFileURL(path.resolve(__dirname, '../index.html')).href;
const results = [];
const pass = text => { results.push(text); console.log('PASS', text); };
let browser;
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  await page.waitForFunction(() => [...document.images].every(i => i.complete));
  assert.equal(await page.locator('.mode-card').count(), 4);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: path.join(out, 'desktop-home.png'), fullPage: true });
  pass('Offline file opens; four modes and all initial images load');
  await page.locator('#startButton').click();
  await page.waitForFunction(() => document.querySelectorAll('[data-zone^="g"]').length === 3);
  const data = await page.evaluate(() => ({ q: state.q, tokens: state.tokens.length }));
  assert.deepEqual(data.q, { a: 3, b: 2, op: '×', answer: 6 });
  assert.equal(data.tokens, 6);
  assert.equal(await page.locator('#miniEquation').isVisible(), false);
  await page.screenshot({ path: path.join(out, 'desktop-play.png'), fullPage: true });
  const dragTo = async (source, destination) => {
    const from = await page.locator(source).first().boundingBox();
    const to = await page.locator(destination).boundingBox();
    assert.ok(from && to, 'drag endpoints exist');
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
    await page.mouse.down();
    await page.mouse.move(to.x + to.width / 2, to.y + 65, { steps: 12 });
    await page.mouse.up();
  };
  await dragTo('#supplyItems [data-token]', '[data-zone="g0"]');
  assert.deepEqual(await page.evaluate(() => counts()), [1, 0, 0]);
  assert.equal(await page.locator('#supplyItems [data-token]').count(), 5);
  assert.equal(await page.locator('#badge0').textContent(), '1');
  await dragTo('#extract0 [data-token]', '[data-zone="pool"]');
  assert.deepEqual(await page.evaluate(() => counts()), [0, 0, 0]);
  assert.equal(await page.locator('#supplyItems [data-token]').count(), 6);
  await dragTo('#supplyItems [data-token]', '[data-zone="g0"]');
  await page.locator('#undoButton').click();
  assert.deepEqual(await page.evaluate(() => counts()), [0, 0, 0]);
  pass('Real mouse drag moves exactly one item; extracting and undo conserve objects');
  // A drag ending outside every target must leave the model unchanged.
  const source = await page.locator('#supplyItems [data-token]').first().boundingBox();
  await page.mouse.move(source.x + 20, source.y + 20); await page.mouse.down();
  await page.mouse.move(5, 5, { steps: 5 }); await page.mouse.up();
  assert.deepEqual(await page.evaluate(() => counts()), [0, 0, 0]);
  await page.locator('#checkButton').click();
  assert.equal(await page.evaluate(() => state.solved), false);
  for (let group = 0; group < 3; group++) for (let j = 0; j < 2; j++) await dragTo('#supplyItems [data-token]', `[data-zone="g${group}"]`);
  assert.deepEqual(await page.evaluate(() => counts()), [2, 2, 2]);
  await page.locator('#checkButton').click();
  assert.equal(await page.locator('.reveal').textContent(), '3 × 2 = 6');
  const stars = await page.evaluate(() => save.stars);
  await page.evaluate(() => { check(); success(); });
  assert.equal(await page.evaluate(() => save.stars), stars);
  pass('Arrangement required; completed equation revealed; duplicate reward blocked');
  await page.locator('[data-action="next"]').click();
  await page.locator('[data-op="−"]').click();
  const sub = await page.evaluate(() => state.q);
  assert.equal(await page.locator('#badge0').textContent(), String(sub.a));
  for (let i = 0; i < sub.b; i++) await dragTo('#extract0 [data-token]', '[data-zone="take"]');
  assert.equal(await page.evaluate(() => arranged()), true);
  await page.locator('#checkButton').click();
  assert.equal(await page.locator('.reveal').textContent(), `${sub.a} − ${sub.b} = ${sub.answer}`);
  pass('Subtraction starts full and validates both remaining and taken-away objects');
  await page.evaluate(() => goHome());
  await page.locator('[data-mode="look"]').click();
  assert.equal(await page.locator('.picture-group').count(), 5);
  assert.equal(await page.locator('.picture-group img').count(), 20);
  await page.locator('#lookInput0').fill('4'); await page.locator('#lookInput1').fill('5'); await page.locator('#lookInput2').fill('20');
  await page.locator('#checkButton').click();
  assert.equal(await page.evaluate(() => state.solved), false);
  assert.match(await page.locator('#guideText').textContent(), /乘积算对了/);
  await page.locator('#lookInput0').fill('5'); await page.locator('#lookInput1').fill('4');
  await page.screenshot({ path: path.join(out, 'desktop-exam.png'), fullPage: true });
  await page.locator('#checkButton').click();
  assert.equal(await page.evaluate(() => state.solved), true);
  pass('Exam example is five groups of four; factor labels and total are validated');
  await page.evaluate(() => goHome()); await page.locator('[data-mode="drill"]').click();
  const answer = await page.evaluate(() => state.q.answer);
  assert.equal(await page.locator('[data-choice]').count(), 4);
  await page.locator(`[data-choice="${answer}"]`).click(); await page.locator('#checkButton').click();
  assert.equal(await page.evaluate(() => state.solved), true);
  await page.locator('[data-action="next"]').click();
  await page.locator('[data-tab="input"]').click();
  await page.locator('#numberAnswer').fill(String(await page.evaluate(() => state.q.answer)));
  await page.locator('#numberAnswer').press('Enter');
  assert.equal(await page.evaluate(() => state.solved), true);
  await page.locator('[data-action="next"]').click(); await page.locator('[data-tab="link"]').click();
  const links = await page.evaluate(() => state.linkQuestions.map(q => state.linkOptions.indexOf(q.answer)));
  await page.locator('[data-linkq="0"]').click(); await page.locator('[data-linka="0"]').click();
  await page.locator('[data-linkq="1"]').click(); await page.locator('[data-linka="0"]').click();
  assert.equal(await page.evaluate(() => state.pairs.length), 1);
  for(let qi=0;qi<3;qi++){await page.locator(`[data-linkq="${qi}"]`).click();await page.locator(`[data-linka="${links[qi]}"]`).click();}
  await page.locator('#checkButton').click(); assert.equal(await page.evaluate(() => state.solved), true);
  pass('Choice, keyboard input, and real one-to-one matching lines work');
  await page.evaluate(() => goHome()); await page.locator('[data-mode="mix"]').click();
  await page.evaluate(() => { save.settings.timed=true; startTimer(); });
  await page.locator('#settingsButton').click();
  const paused=await page.evaluate(()=>state.timeLeft);await page.waitForTimeout(400);
  assert.equal(await page.evaluate(()=>state.timeLeft),paused);
  await page.locator('[data-action="close"]').click();
  await page.evaluate(()=>{state.timeLeft=.01;});await page.waitForTimeout(250);
  assert.equal(await page.evaluate(()=>state.solved),false);
  assert.equal(await page.evaluate(()=>state.timerExpired),true);
  await page.evaluate(()=>goHome());
  assert.equal(await page.evaluate(()=>state.timer),null);
  pass('Challenge timer pauses in settings, allows thought after expiry, and stops at home');
  const invariant = await page.evaluate(() => {
    for(const op of ['×','÷','+','−'])for(const difficulty of ['easy','medium','hard'])for(let i=0;i<100;i++){
      const q=makeQuestion(op,difficulty,true),tokens=createTokens(q),targets=groupTargets(q);
      if(q.answer<0||q.answer%1||tokens.length!==totalObjects(q))throw Error('invalid generated arithmetic');
      let index=0;targets.forEach((n,g)=>{for(let j=0;j<n;j++)tokens[index++].zone='g'+g;});
      if(q.op==='−')while(index<tokens.length)tokens[index++].zone='take';
      if(!arranged(q,tokens))throw Error('valid solution rejected');
      const bad=tokens.map(t=>({...t}));bad[0].zone='invalid';if(arranged(q,bad))throw Error('invalid object accepted');
    }
    return true;
  });
  assert.ok(invariant);pass('1,200 generated visual questions satisfy arithmetic and object-conservation invariants');
  // All item/container/background combinations are real files and decode correctly.
  const assets=await page.evaluate(async()=>{
    const keys=[...new Set(THEMES.flatMap(t=>['item_'+t.item,'container_'+t.container,'bg_'+t.bg]))];
    return Promise.all(keys.map(key=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve({key,ok:im.naturalWidth>0});im.onerror=()=>resolve({key,ok:false});im.src='images/'+key+'.png';})));
  });assert.ok(assets.every(x=>x.ok));pass(`${assets.length} scene, counting, and container bitmap assets verified`);
  await page.locator('#soundToggle').click();
  assert.equal(await page.evaluate(()=>save.settings.sound),false);
  await page.reload();assert.equal(await page.evaluate(()=>save.settings.sound),false);
  assert.equal(await page.evaluate(()=>save.stars),stars+5);
  pass('Mute preference and earned stars survive reload');
  await page.locator('[data-mode="mix"]').click();
  const kinds = new Set();
  for(let i=0;i<10;i++){
    kinds.add(await page.evaluate(()=>state.kind));
    await page.evaluate(()=>{
      if(state.kind==='play'){
        let index=0;
        groupTargets(state.q).forEach((n,g)=>{for(let j=0;j<n;j++)moveToken(state.tokens[index++].id,'g'+g);});
        if(state.q.op==='−')while(index<state.tokens.length)moveToken(state.tokens[index++].id,'take');
      }else if(state.kind==='look'){
        state.inputs=[state.q.a,state.q.b,state.q.answer].map(String);renderLook();
      }else{state.choice=state.q.answer;renderDrill();}
    });
    await page.locator('#checkButton').click();
    assert.equal(await page.evaluate(()=>state.solved),true);
    await page.locator('[data-action="next"]').click();
  }
  assert.equal(kinds.size,3);
  assert.equal(await page.evaluate(()=>state.correct),10);
  assert.equal(await page.evaluate(()=>state.score),18);
  assert.match(await page.locator('#modalTitle').textContent(),/冒险完成/);
  await page.locator('[data-action="home"]').click();
  pass('Full ten-question mixed challenge cycles all three activities and awards the trophy once');
  await page.locator('#soundToggle').click();
  await page.waitForTimeout(650);
  const sound=await page.evaluate(async()=>{
    const analyser=audio.ctx.createAnalyser();analyser.fftSize=2048;audio.master.connect(analyser);
    const values=new Float32Array(analyser.fftSize);let peak=0;
    for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,70));analyser.getFloatTimeDomainData(values);peak=Math.max(peak,...values.map(Math.abs));}
    audio.master.disconnect(analyser);return {peak,state:audio.ctx.state};
  });
  assert.equal(sound.state,'running');assert.ok(sound.peak>0,'audio produces a signal');
  await page.locator('#soundToggle').click();await page.waitForTimeout(500);
  assert.ok(await page.evaluate(()=>audio.master.gain.value<.001));
  pass('Music produces a real audio signal after interaction; mute ramps output to silence');
  const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  const touch=await mobile.newPage();touch.on('pageerror',e=>errors.push(e.message));await touch.goto(url);await touch.screenshot({path:path.join(out,'phone-home.png'),fullPage:true});
  await touch.locator('#startButton').tap();
  assert.equal(await touch.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const touchFrom=await touch.locator('#supplyItems [data-token]').first().boundingBox(),touchTo=await touch.locator('[data-zone="g0"]').boundingBox();
  const cdp=await mobile.newCDPSession(touch);
  const x=touchFrom.x+touchFrom.width/2,y=touchFrom.y+touchFrom.height/2,tx=touchTo.x+touchTo.width/2,ty=touchTo.y+65;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
  for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(tx-x)*i/12,y:y+(ty-y)*i/12}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.deepEqual(await touch.evaluate(()=>counts()),[1,0,0]);
  await touch.screenshot({path:path.join(out,'phone-play.png'),fullPage:true});
  const before=await touch.evaluate(()=>JSON.stringify(state.tokens));
  const cancelFrom=await touch.locator('#supplyItems [data-token]').first().boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cancelFrom.x+20,y:cancelFrom.y+20}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  assert.equal(await touch.evaluate(()=>JSON.stringify(state.tokens)),before);
  assert.equal(await touch.locator('#dragGhost').isVisible(),false);
  pass('Real Chromium touch drag and touch cancellation work at 390px with no horizontal overflow');
  await touch.setViewportSize({width:768,height:1024});await touch.evaluate(()=>goHome());await touch.locator('[data-mode="look"]').tap();
  assert.equal(await touch.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await touch.screenshot({path:path.join(out,'tablet-exam.png'),fullPage:true});
  pass('Tablet exam layout has no horizontal overflow');
  await touch.setViewportSize({width:320,height:568});
  await touch.evaluate(()=>{goHome();startMode('play');state.q={a:5,b:6,op:'×',answer:30};state.tokens=createTokens(state.q);state.initial=state.tokens.map(t=>({...t}));renderQuestion();});
  assert.equal(await touch.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  // Drag to a lower group using the built-in edge autoscroll, without releasing the touch.
  await touch.locator('#supplyItems [data-token]').first().scrollIntoViewIfNeeded();
  const smallSource=await touch.locator('#supplyItems [data-token]').first().boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:smallSource.x+23,y:smallSource.y+23}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:80,y:550}]});
  await touch.waitForFunction(()=>document.querySelector('[data-zone="g4"]').getBoundingClientRect().top<350);
  const lower=await touch.locator('[data-zone="g4"]').boundingBox();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:lower.x+lower.width/2,y:lower.y+65}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal(await touch.evaluate(()=>counts()[4]),1);
  pass('320px hard-level layout fits; held touch autoscroll reaches the fifth group');
  assert.deepEqual(errors,[]);pass('No JavaScript runtime errors');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({date:new Date().toISOString(),checks:results},null,2));
  await browser.close();
})().catch(async error=>{console.error(error);if(browser)await browser.close();process.exitCode=1;});
